import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { createExclusionFilter, isExcludedPath } from "../../../src/detect/exclusions.js";

describe("detect/exclusions", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "specty-exclusions-test-"));
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it("filters default excluded directories and autogenerated code", async () => {
    const filter = await createExclusionFilter(tempDir);

    expect(isExcludedPath("node_modules/foo/index.js", filter)).toBe(true);
    expect(isExcludedPath("vendor/autoload.php", filter)).toBe(true);
    expect(isExcludedPath("bin/Debug/app.dll", filter)).toBe(true);
    expect(isExcludedPath("obj/Release/app.o", filter)).toBe(true);
    expect(isExcludedPath("dist/index.js", filter)).toBe(true);
    expect(isExcludedPath("build/main.js", filter)).toBe(true);
    expect(isExcludedPath("target/classes/App.class", filter)).toBe(true);
    expect(isExcludedPath("lib/models/user.g.dart", filter)).toBe(true);
    expect(isExcludedPath("lib/models/user.freezed.dart", filter)).toBe(true);
    expect(isExcludedPath(".env", filter)).toBe(true);
    expect(isExcludedPath(".env.production", filter)).toBe(true);

    expect(isExcludedPath("src/index.ts", filter)).toBe(false);
    expect(isExcludedPath("lib/main.dart", filter)).toBe(false);
  });

  it("incorporates custom repository .gitignore rules", async () => {
    await fs.writeFile(path.join(tempDir, ".gitignore"), "custom-temp/\n*.log\n");
    const filter = await createExclusionFilter(tempDir);

    expect(isExcludedPath("custom-temp/file.txt", filter)).toBe(true);
    expect(isExcludedPath("app.log", filter)).toBe(true);
    expect(isExcludedPath("src/app.ts", filter)).toBe(false);
  });
});
