import path from "node:path";
import type { SupportedLanguage } from "../core/i18n.js";
import type { GeneratedFile } from "../generate/types.js";
import type { AdapterContext, ToolAdapter } from "./types.js";

const CHATGPT_INSTRUCTIONS_PATH = ".specty/exports/chatgpt-instructions.md";
const OPENAI_CONTEXT_PATH = ".specty/exports/openai-context.md";

function buildChatGptInstructions(lang: SupportedLanguage): string {
  if (lang === "es") {
    return `# Instrucciones del Sistema para ChatGPT Projects / Canvas

Eres un asistente de desarrollo regido por la gobernanza de **specty**.

## Regla Soberana
La unica fuente de verdad para directivas, flujos, roles y restricciones tecnicas es **AGENTS.md**.

## Protocolo Obligatorio
1. **Nunca escribas codigo** sin una especificacion de cambio aprobada en \`openspec/changes/<change>/\`.
2. Adopta el rol correspondiente segun la tarea antes de generar o modificar codigo:
   - \`orchestrator\`: Planificacion y descomposicion.
   - \`frontend\` / \`backend\` / \`data\`: Implementacion especializada.
   - \`testing\`: Casos de prueba y cobertura.
   - \`security-review\`: Analisis de vulnerabilidades.
3. Respeta siempre los comandos de verificacion y quality gates antes de dar por finalizada cualquier modificacion.
4. Genera commits en formato estricto: \`<type>(<scope>): <descripcion en minusculas>\`.
`;
  }

  return `# System Instructions for ChatGPT Projects / Canvas

You are a software engineering assistant governed by **specty**.

## Sovereign Rule
The single source of truth for directives, workflows, roles, and constraints is **AGENTS.md**.

## Mandatory Protocol
1. **Never write code** without a human-approved change specification in \`openspec/changes/<change>/\`.
2. Adopt the designated role prior to acting:
   - \`orchestrator\`: Scope and task decomposition.
   - \`frontend\` / \`backend\` / \`data\`: Specialized implementation.
   - \`testing\`: Test cases and coverage validation.
   - \`security-review\`: Security and boundary audits.
3. Always verify changes using configured verification commands and quality gates.
4. Use strict Conventional Commits: \`<type>(<scope>): <lowercase description>\`.
`;
}

function buildOpenAiContextBundle(ctx: AdapterContext): string {
  const primaryScope = ctx.config.scopes[0];
  const lang = primaryScope?.stack.language ?? "typescript";
  const frameworks = primaryScope?.stack.frameworks?.join(", ") || "none";
  const architecture = ctx.config.project?.architecture ?? "clean";
  const projectName = path.basename(ctx.repoRoot);
  const verify = ctx.config.scopes[0]?.verify ?? {};
  const isEs = ctx.language === "es";

  const verifyLines =
    Object.entries(verify)
      .filter(([_, cmd]) => Boolean(cmd))
      .map(([key, cmd]) => `- **${key}**: \`${cmd}\``)
      .join("\n") ||
    (isEs
      ? "- Comandos de verificacion estandar segun config."
      : "- Standard verification commands per config.");

  if (isEs) {
    return `# Paquete de Contexto Compacto: ${projectName}
> Generado por Specty para OpenAI Canvas y ChatGPT Projects.

## 1. Perfil del Proyecto
- **Proyecto**: \`${projectName}\`
- **Lenguaje Principal**: \`${lang}\`
- **Frameworks**: \`${frameworks}\`
- **Arquitectura**: \`${architecture}\`
- **Motor de Especificacion**: \`${ctx.config.spec_engine}\`

## 2. Directiva Soberana
Este proyecto sigue gobernanza estricta guiada por especificaciones. Toda accion de programacion debe basarse en una propuesta aprobada en \`openspec/changes/<change>/\`.
- **Fuente de Verdad**: \`AGENTS.md\`
- **Enrutamiento de Roles**: \`.specty/routing.md\`
- **Reglas Modulares**: \`.specty/rules/\`

## 3. Matriz de Roles
| Rol | Responsabilidad Clave |
| :--- | :--- |
| **orchestrator** | Disena la propuesta, desglosa tareas y coordina transiciones. |
| **frontend** | Implementa componentes UI y logica de presentacion. |
| **backend** | Desarrolla logica de negocio, servicios y capas de dominio. |
| **data** | Modela esquemas, migraciones y persistencia. |
| **testing** | Implementa suites unitarias, de integracion y e2e. |
| **security-review** | Audita superficies de ataque y valida cumplimiento. |

## 4. Comandos de Verificacion
${verifyLines}

## 5. Reglas de Codificacion y Git
- Prioriza simplicidad y consistencia con el codigo existente.
- No introduzcas dependencias externas sin verificacion previa.
- Commits obligatorios: \`<type>(<scope>): <descripcion>\` (tipos: feat, fix, refactor, test, docs, chore).
`;
  }

  return `# Compact Context Bundle: ${projectName}
> Generated by Specty for OpenAI Canvas and ChatGPT Projects.

## 1. Project Profile
- **Project**: \`${projectName}\`
- **Primary Language**: \`${lang}\`
- **Frameworks**: \`${frameworks}\`
- **Architecture**: \`${architecture}\`
- **Spec Engine**: \`${ctx.config.spec_engine}\`

## 2. Sovereign Directive
This project enforces specification-driven AI governance. All coding tasks must be anchored in an approved change proposal in \`openspec/changes/<change>/\`.
- **Single Source of Truth**: \`AGENTS.md\`
- **Role Routing Matrix**: \`.specty/routing.md\`
- **Modular Rules**: \`.specty/rules/\`

## 3. Role Matrix
| Role | Core Responsibility |
| :--- | :--- |
| **orchestrator** | Proposal design, task breakdown, handoffs. |
| **frontend** | UI components and presentation logic. |
| **backend** | Domain services, business logic, endpoints. |
| **data** | Schemas, persistence, database migrations. |
| **testing** | Unit, integration, and e2e test suites. |
| **security-review** | Vulnerability audits and boundary checks. |

## 4. Verification Commands
${verifyLines}

## 5. Coding Principles and Git
- Prioritize functional simplicity and existing patterns.
- Do not introduce external dependencies without verification.
- Mandatory commits: \`<type>(<scope>): <description>\` (types: feat, fix, refactor, test, docs, chore).
`;
}

export const chatgptAdapter: ToolAdapter = {
  id: "chatgpt",
  name: "OpenAI Canvas / ChatGPT Projects",

  async generateFiles(ctx: AdapterContext): Promise<GeneratedFile[]> {
    return [
      {
        relativePath: CHATGPT_INSTRUCTIONS_PATH,
        content: buildChatGptInstructions(ctx.language),
        description: "Compact system instructions for ChatGPT Project / Custom Instructions",
      },
      {
        relativePath: OPENAI_CONTEXT_PATH,
        content: buildOpenAiContextBundle(ctx),
        description: "Compact context bundle for OpenAI Canvas and ChatGPT Project Files",
      },
    ];
  },

  getExpectedFilePaths(): string[] {
    return [CHATGPT_INSTRUCTIONS_PATH, OPENAI_CONTEXT_PATH];
  },

  getMcpInstructions(language: SupportedLanguage): string {
    if (language === "es") {
      return "OpenAI Canvas y ChatGPT Projects operan en la nube y no soportan MCP local directo por stdio. specty genera paquetes compactos en '.specty/exports/' para ser importados en las instrucciones y archivos del proyecto.";
    }
    return "OpenAI Canvas and ChatGPT Projects are cloud-hosted and do not support local stdio MCP servers. specty generates compact bundles in '.specty/exports/' to be loaded into Project Instructions and Project Files.";
  },
};
