export const VERSION = "0.1.0";
export const PACKAGE_NAME = "@barcidev/specty";
export const BINARY_NAME = "specty";

export * as adapters from "./adapters/index.js";
export * from "./adapters/index.js";
export * as core from "./core/index.js";
export * from "./core/index.js";
export * as detect from "./detect/index.js";
export * from "./detect/index.js";
export * as engines from "./engines/index.js";
export * from "./engines/index.js";
export * as generate from "./generate/index.js";
export * from "./generate/index.js";
export * as governance from "./governance/index.js";
export * from "./governance/index.js";
export * as handoff from "./handoff/index.js";
export * from "./handoff/index.js";
export * as mcp from "./mcp/index.js";
export * from "./mcp/index.js";
export * as metrics from "./metrics/index.js";
export * from "./metrics/index.js";
